[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pump= "DJMMfpsEPB6JSpzakCK9CqBtAjzRhFx7AYNUAqVktmUE"
pump_game= "AGAtML592JZnHBjDDEZ97DGNy9jwETaPiAxtrBfcXFaX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/siddi_404/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
