[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump = "C2Bj5sizbDg41KzZj1EnCrC3Dg8yCmZVvazQJzWDY8U8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/siddi_404/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
